Controllers/PreviewController.cs
using Microsoft.AspNetCore.Mvc;

namespace Save__plan_your_trips.Controllers
{
    public class PreviewController : Controller
    {
        [RedirectToAuthenticatedUserHomePageAttribute]
        public IActionResult StarterPage()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Controllers/ScheduledController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Save__plan_your_trips.Data;
using Save__plan_your_trips.Models.Domain;
using Save__plan_your_trips.Models.ViewModels;
using Save__plan_your_trips.Repositories;

namespace Save__plan_your_trips.Controllers;

[Authorize]
public class ScheduledController : Controller
{
    private readonly ScheduledRepository? scheduledRepository;

    public ScheduledController(IScheduledRepository scheduledRepository)

    {
        this.scheduledRepository = (ScheduledRepository?)scheduledRepository;
    }

    [HttpGet]
    public async Task<IActionResult> ScheduledTrips()
    {
        var scheduledTrips = (await scheduledRepository.GetAllScheduledTrips()).OrderBy(x => x.DateTime);
        var todos = await scheduledRepository.GetAllToDos();

        var plannedToDos = todos.Where(todo => !todo.IsPerformed).ToList();
        var performedToDos = todos.Where(todo => todo.IsPerformed).ToList();

        var scheduledTripsPageViewModel = new ScheduledTripsPageViewModel
        {
            ScheduledTrips = scheduledTrips,
            PlannedToDos = plannedToDos,
            PerformedToDos = performedToDos,
            ToDos = todos,
        };

        return View(scheduledTripsPageViewModel);
    }

    [HttpGet]
    public IActionResult AddScheduledTripName()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> AddScheduledTripName(AddScheduledTripNameRequest addScheduledTripNameRequest)
    {
        var scheduledTrip = new ScheduledTrip
        {
            Name = addScheduledTripNameRequest.Name,
        };

        if (ModelState.IsValid)
        {
            await scheduledRepository.AddScheduledTrip(scheduledTrip);
            return RedirectToAction("AddScheduledTrip", new { id = scheduledTrip.Id });
        }

        return RedirectToAction("AddScheduledTripName");
    }

    [HttpGet]
    public async Task<IActionResult> AddScheduledTrip(Guid id)
    {
        var scheduledTrip = await scheduledRepository.GetSingleAsync(id);

        if (scheduledTrip == null)
        {
            return NotFound();
        }

        var model = new AddScheduledTripViewModel
        {
            ScheduledTrip = scheduledTrip,
            ToDoList = scheduledTrip?.ToDos,
        };

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> AddScheduledTripDate(AddScheduledTripDateRequest addScheduledTripDateRequest)
    {
        if (ModelState.IsValid)
        {
            var scheduledTripDateTime = new ScheduledTrip
            {
                Id = addScheduledTripDateRequest.Id,
                DateTime = addScheduledTripDateRequest.DateTime,
            };

            await scheduledRepository.SubmitDate(scheduledTripDateTime);
            return RedirectToAction("ScheduledTrips");
        }

        return NotFound();
    }

    [HttpPost]
    public async Task<IActionResult> AddToDo(AddToDoRequest addToDoRequest)
    {
        if (ModelState.IsValid)
        {
            var todo = new ToDo
            {
                Task = addToDoRequest.Task,
                ScheduledTripId = addToDoRequest.ScheduledTripId,
            };

            await scheduledRepository.AddToDo(todo);
        }

        if (!string.IsNullOrEmpty(addToDoRequest.ReturnUrl))
        {
            return Redirect(addToDoRequest.ReturnUrl);
        }

        return RedirectToAction("AddScheduledTrip", new { id = addToDoRequest.ScheduledTripId });
    }

    [HttpPost]
    public async Task<IActionResult> PerformToDos(List<PerformToDoRequest> performToDoRequests)
    {
        foreach (var performToDoRequest in performToDoRequests)
        {
            var todo = await scheduledRepository.GetSingleToDo(performToDoRequest.Id);
            if (todo != null)
            {
                todo.IsPerformed = performToDoRequest.IsPerformed;
                await scheduledRepository.SaveChangesAsync();
            }
        }

        return RedirectToAction("ScheduledTrips");
    }
    
    [HttpPost]
    public async Task<IActionResult> UnperformToDos(List<UnperformToDoRequest> unperformToDoRequests)
    {
        foreach (var unperformToDoRequest in unperformToDoRequests)
        {
            var todo = await scheduledRepository.GetSingleToDo(unperformToDoRequest.Id);
            if (todo != null )
            {
                todo.IsPerformed = !unperformToDoRequest.IsPerformed;
                await scheduledRepository.SaveChangesAsync();
            }
        }

        return RedirectToAction("ScheduledTrips");
    }

    [HttpGet]
    public async Task<IActionResult> EditScheduledTrip(Guid id)
    {
        var scheduledTrip = await scheduledRepository.GetSingleAsync(id);
        if (scheduledTrip == null) return NotFound();
        var model = new AddScheduledTripViewModel
        {
            EditScheduledTripRequest = new EditScheduledTripRequest
            {
                Id = scheduledTrip.Id,
                Name = scheduledTrip.Name,
                DateTime = scheduledTrip.DateTime,
            },
            ScheduledTrip = scheduledTrip,
            ToDoList = scheduledTrip?.ToDos,
        };

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> EditScheduledTrip(EditScheduledTripRequest editScheduledTripRequest)
    {
        var editedScheduledTrip = new ScheduledTrip
        {
            Id = editScheduledTripRequest.Id,
            Name = editScheduledTripRequest.Name,
            DateTime = editScheduledTripRequest.DateTime,
        };

        await scheduledRepository.EditScheduledTrip(editedScheduledTrip);
        return RedirectToAction("ScheduledTrips");
    }

    [HttpPost]
    public async Task<IActionResult> DeleteScheduledTrip(EditScheduledTripRequest editScheduledTripRequest)
    {
        var deletedScheduledTrip = await scheduledRepository.DeleteScheduledTrip(editScheduledTripRequest.Id);
        if (deletedScheduledTrip != null)
            return RedirectToAction("ScheduledTrips");
        return RedirectToAction("EditScheduledTrip", new { id = editScheduledTripRequest.Id });
    }

    [HttpPost]
    public async Task<IActionResult> DeleteToDo(DeleteToDoRequest deleteToDoRequest)
    {
        await scheduledRepository.DeleteToDo(deleteToDoRequest.Id);
        if (!string.IsNullOrEmpty(deleteToDoRequest.ReturnUrl))
        {
            return Redirect(deleteToDoRequest.ReturnUrl);
        }

        return NotFound();
    }
}

Controllers/TripsController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Save__plan_your_trips.Models.Domain;
using Save__plan_your_trips.Models.ViewModels;
using Save__plan_your_trips.Repositories;
using Image = Save__plan_your_trips.Models.Domain.Image;


namespace Save__plan_your_trips.Controllers;

[Authorize]
public class TripsController : Controller
{
    private readonly ITripsRepository tripsRepository;

    public TripsController(ITripsRepository tripsRepository)
    {
        this.tripsRepository = tripsRepository;
    }

    [HttpGet]
    public async Task<IActionResult> YourAlbums()
    {
        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier); 
        
        var albums = new YourAlbumsPageViewModel
        {
            Albums = await tripsRepository.GetAlbums(),
        };

        return View(albums);
    }

    [HttpGet]
    [HttpPost]
    public async Task<ActionResult> AddAlbum(AddAlbumRequest addAlbumRequest)
    {
        if (!ModelState.IsValid) return View();

        var album = new Album
        {
            Name = addAlbumRequest.Place.Name,
        };

        await tripsRepository.AddAlbum(album);

        if (addAlbumRequest.Images?.File != null)
            foreach (var imageRequest in addAlbumRequest.Images.File)
            {
                var image = new Image
                {
                    AlbumId = album.Id,
                };
                await tripsRepository.AddImage(image, imageRequest);
            }

        return RedirectToAction("YourAlbums");
    }

    [HttpGet]
    public async Task<IActionResult> EditAlbum(Guid id)
    {
        var album = await tripsRepository.GetSingle(id);
        if (album == null) return View(null);
        var model = new EditAlbumRequest
        {
            Id = album.Id,
            Name = album.Name,
            Images = new List<Image>(),
            ImageUrls = string.Join("\n\n", album.Images.Select(i => i.Url)),
        };
        foreach (var image in album.Images)
        {
            var existingImage = new Image { Url = image.Url };
            model.Images.Add(existingImage);
        }

        return View(model);
    }

    [HttpPost]
    public async Task<IActionResult> EditAlbum(EditAlbumRequest editAlbumRequest)
    {
        var editedAlbum = new Album
        {
            Id = editAlbumRequest.Id,
            Name = editAlbumRequest.Name,
        };

        if (editAlbumRequest.AddImageRequest.File != null)
        {
            foreach (var imageRequest in editAlbumRequest.AddImageRequest.File)
            {
                var image = new Image
                {
                    AlbumId = editAlbumRequest.Id,
                    Url = editAlbumRequest.ImageUrls,
                };
                await tripsRepository.AddImage(image, imageRequest);
            }
        }

        var result = await tripsRepository.EditAlbum(editedAlbum);
        if (result != null)
            return RedirectToAction("YourAlbums");
        return RedirectToAction("EditAlbum");
    }

    [HttpPost]
    public async Task<IActionResult> DeleteAlbum(EditAlbumRequest editAlbumRequest)
    {
        var deletedAlbum = await tripsRepository.DeleteAlbum(editAlbumRequest.Id);

        if (deletedAlbum != null)
            return RedirectToAction("YourAlbums");
        return RedirectToAction("EditAlbum", new { id = editAlbumRequest.Id });
    }

    [HttpPost]
    public async Task<IActionResult> DeleteImage(DeleteImageRequest deleteImageRequest)
    {
        await tripsRepository.DeleteImage(deleteImageRequest.Id);

        return RedirectToAction("YourAlbums");
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Trips Manager</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100..700;1,100..700&family=Rubik:ital,wght@0,300..900;1,300..900&display=swap"
        rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        html {
            font-size: 62.5%;
        }

        body {
            font-size: 1.6rem;
            font-family: "Rubik", sans-serif;
            line-height: 1.5;
            font-weight: 400;
            color-scheme: light dark;
            color: #ddd;
            background-color: #242424;
        }

        input {
            background-color: #333;
            border: none;
            border-radius: 6px;
            padding: 1.2rem;
        }

        textarea {
            background-color: #333;
        }

        button {
            border-radius: 6px;
            border: 1px solid transparent;
            padding: 0.6em 1.2em;
            font-size: 1.6rem;
            font-weight: 500;
            font-family: inherit;
            background-color: #15aabf;
            color: #242424;
            cursor: pointer;
            transition: all 0.2s
        }

        button:hover {
            background-color: #22b8cf;
        }

        button:focus,
        button:focus-visible {
            outline: 4px auto -webkit-focus-ring-color;
        }

        .nav ul {
            list-style: none;
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 2.4rem;
            background-color: #22b8cf;
        }

        .mainPages {
            display: flex;
            gap: 1.6rem;
            align-items: center;
        }

        .nav a {
            font-weight: 600;
            text-decoration: none;
            color: #242424;
            transition: all 0.3s;
        }

        .nav a:hover {
            color: #096072;
        }
        
        .authPages {
            display: flex;
            gap: 1.6rem;
        }

        .userName {
            color: #333;
        }

        @@media screen and (max-width: 1600px) {
            html{
                font-size: 58%;
            }
        }
        
        @@media screen and (max-width: 768px) {
           html{
              font-size: 55%;
           }
        } 
        @@media screen and (max-width: 500px) {
           html{
              font-size: 45%;
           }
        }  
        @@media screen and (max-height: 750px) {
            h2{
                margin-bottom: 1.2rem;
            }
            html{
                font-size: 48%;
            }
        }

        @@keyframes fadeIn {
            0% {opacity: 0.8;}
            100% {opacity: 1;}
        }
         
        
    </style>
</head>

@inject SignInManager<IdentityUser> SignInManager

<body>
<header>
    <nav class="nav">
        <ul>
            <div class="mainPages">
                @if (SignInManager.IsSignedIn(User))
                {
                <li>
                    <a asp-area="" asp-controller="Home" asp-action="Index">
                        Home
                    </a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Trips" asp-action="YourAlbums">Trips</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Scheduled" asp-action="ScheduledTrips">Scheduled</a>
                </li>
                }
                else
                {
                <li>
                    <a asp-area="" asp-controller="Preview" asp-action="StarterPage">Home</a>
                </li>
                }
            </div>
            <div class="authPages">
                @if (SignInManager.IsSignedIn(User))
                {
                <div class="userName">@User.Identity?.Name</div>
                <li>
                    <a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                </li>
                }
                else
                {
                <li>
                    <a asp-area="" asp-controller="Account" asp-action="Login">Sign In</a>
                </li>
                <li>
                    <a asp-area="" asp-controller="Account" asp-action="SignUp">Sign Up</a>
                </li>
                }
            </div>
        </ul>
    </nav>
</header>
<div>
    <main role="main">
        @RenderBody()
    </main>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>